### ISSUE TITLE
Symbol not found: _getentropy

### ISSUE THREAD

**Issue by sursh** [iterative/homebrew-dvc#7]
Hi there, I'm hitting some installation issues. If using the pkg from your website or homebrew+cask, I can successfully install dvc. However, it throws this error every time it runs: 

``` $ dvc help
[12278] Error loading Python lib '/var/folders/97/hrh_5ys15f556n7r6v3_s4814y3218/T/_MEIx60IU1/Python': dlopen: dlopen(/var/folders/97/hrh_5ys15f556n7r6v3_s4814y3218/T/_MEIx60IU1/Python, 10): Symbol not found: _getentropy
  Referenced from: /var/folders/97/hrh_5ys15f556n7r6v3_s4814y3218/T/_MEIx60IU1/Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/97/hrh_5ys15f556n7r6v3_s4814y3218/T/_MEIx60IU1/Python
```

I'm running OS 10.11.6 and I generally use my Anaconda Python3, but it looks like this is using some other Python, and one that says it's built for 10.13. Is that a requirement of dvc?

**Comment by efiop** [comment]
Hi @sursh !

Our pkg is built using PyInstaller into a binary package and includes everything to run dvc on other systems, including python itself. The cask is just installing that same package. Looks like the issue here is in that we are not resetting LD_LIBRARY_PATH properly somewhere in our code, thus causing built-in python to access something from outside of the temporary directory that it should've used. I'm looking into it right now. In the meantime, you could try installing dvc from pip with `pip install dvc`, which should work without any issues, since pip package is not built using PyInstaller and thus not affected by this bug.

Thank you for the feedback!

-Ruslan

**Comment by efiop** [comment]
Hi @sursh !

We've released 0.19.1(brew is updated as well), which is now built on OSX 0.10.11 in order to provide future compatibility with newer versions. We've also added tests for 0.10.11-0.10.13 to verify that and make sure that this issue doesn't happen in the future. Please feel free to give it a try.

Thanks,
Ruslan

**Comment by sursh** [comment]
Thanks, installation works via Cask now!!

I did install with pip successfully too, but that doesn't get me the CLI so I'm going to stick to homebrew. Thanks again!

**Comment by efiop** [comment]
Hi @sursh !

Glad it works for you now! :slightly_smiling_face: 

> I did install with pip successfully too, but that doesn't get me the CLI so I'm going to stick to homebrew. 

Hm, maybe I misunderstood something, but why doesn't it get you the CLI ? After `pip install dvc`, dvc should be in your PATH and you should be able to use:
```
$ dvc --help
```
If it doesn't work for you then it seems like there is something wrong with your PATH. Could you please try running:
```
$ python -m dvc
```
and see if this works?

Thanks,
Ruslan

**Comment by sursh** [comment]
I got an error earlier right after installing with pip that it couldn't find /usr/local/bin/dvc. I just tried again and now it's working fine 🤷‍♀️

**Comment by efiop** [comment]
Well, at least it works now :slightly_smiling_face: 

Thanks again for all the feedback!

-Ruslan
